### ISSUE TITLE
Implement the backend service for getting all friends.

### ISSUE THREAD

**Issue by runzeliuzh** [sopra-fs23-group-19/sopra-fs23-group-19-server#36]

**Comment by Shiyu-Ran** [comment]
97a92fcb73fd618ec779d5cd06239e1ab2f8b8e0

**Comment by runzeliuzh** [comment]
Friend overview page https://github.com/sopra-fs23-group-19/sopra-fs23-group-19-client/commit/31e27894136b7f5e13a062232ac394f373907fbb

**Comment by runzeliuzh** [comment]
https://github.com/sopra-fs23-group-19/sopra-fs23-group-19-server/commit/692c2004085f6964b6ec94db619647de031aeb4d
