### ISSUE TITLE
DrawingPlayer-DownloadDrawing-SaveDrawing

### ISSUE THREAD

**Issue by Shiyu-Ran** [sopra-fs23-group-19/sopra-fs23-group-19-server#98]
**Story:** As a drawing player, I would like to have a download option for my favorite drawing.

**Acceptance Criteria:**
- [x] In the drawing phase, near the whiteboard area, there is a “Save” button enabled for the drawing player. 
- [x] Drawing players can save their current drawing result by clicking the "save" button. After the drawing player clicks the “save” button, the image is downloaded locally.
- [x] The save button is still enabled for the drawing player after entering the guessing phase. While waiting for guessing players to submit answers, the drawing player can still click the “Save” button to download his painting. 
- [x] The “save” button would not influence the process of the game.  

**Development Tasks:**
- [x] sopra-fs23-group-19/sopra-fs23-group-19-client#27
- [x] sopra-fs23-group-19/sopra-fs23-group-19-client#28

**Comment by GY-Meng** [comment]
add the save button in guessing stage

**Comment by GY-Meng** [comment]
c11ad8fa8e58e63c7d1d2863abdf289b8b009eac
